# taps
tap 'homebrew/cask'
tap 'homebrew/bundle'

brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'fzf'
brew 'git'
brew 'graphviz'
brew 'jq'
brew 'macvim'
brew 'tmux'
brew 'universal-ctags'

# media
brew 'ffmpeg'
brew 'gifsicle'
brew 'imagemagick'
# giphy capture?
# gif brewery?

# apps
cask '1password'
cask '1password-cli'
cask 'discord'
# cask 'google-chrome'
cask 'slack'
cask 'spectacle'

# Mac App Store
brew 'mas'
mas 'CirclePing', id: 969990150
