# taps
tap 'homebrew/cask'
tap 'homebrew/bundle'

brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'fzf'
brew 'git'
brew 'graphviz'
brew 'jq'
brew 'macvim'
brew 'tmux'
brew 'universal-ctags'

# apps
# cask '1password'
# cask '1password-cli'
# cask 'discord'
# cask 'google-chrome'
# cask 'slack'

# Mac App Store
brew 'mas'
mas 'CirclePing', id: 969990150
