#!/bin/sh

CWD=`pwd`
case $1 in
/*)
  DIR=$1
  ;;
*)
  DIR=$CWD/$1
  ;;
esac

osascript<<END
set thePath to "$DIR"
set thePath to (POSIX path of thePath as string)
tell application "Terminal"
  do script with command "cd " & quoted form of thePath
end tell
END
