if [ `which defaults` ]
then
  # general inspiration (and some specifics) from Mathias Bynens
  # see https://github.com/mathiasbynens/dotfiles/blob/master/.osx

  for f in ${DOTFILES_HOME}osx/*.defaults
  do
    source $f
  done

  # kill affected applications
  #for app in "Dock" "Finder" "iTunes" "SystemUIServer" "Terminal";
  #do
  #  killall "$app" > /dev/null 2>&1
  #done

  echo "OS X defaults written. Note that some of these changes require a logout/restart to take effect."
fi
